services:
  - type: web
    name: erp-distribution
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Wazvu3-ruwzej-wajsop@db.bquxudmlyldlgbjfbmrr.supabase.co:5432/postgres?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: AUTO_CREATE_TABLES
        value: "False"
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        sync: false
      - key: FIRST_ADMIN_PASSWORD
        generateValue: true
      - key: FIRST_ADMIN_USERNAME
        value: admin
      - key: FIRST_ADMIN_FULL_NAME
        value: مدير النظام
    healthCheckPath: /
    autoDeploy: true
