"""add delivery trips and stops

Revision ID: 45655a343b3e
Revises: 90c90a0ec9eb
Create Date: 2026-07-17 01:24:10.653792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45655a343b3e"
down_revision: Union[str, None] = "90c90a0ec9eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_trips",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_date", sa.Date(), nullable=False),
        sa.Column("driver_name", sa.String(length=100), nullable=False),
        sa.Column("vehicle", sa.String(length=100), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("planned", "in_transit", "completed", name="tripstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_trips_trip_date"),
        "delivery_trips",
        ["trip_date"],
        unique=False,
    )
    op.create_table(
        "delivery_stops",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "delivered", "failed", name="stopstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoices.id"],
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["delivery_trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "invoice_id", name="uq_invoice_once_per_trip"),
    )
    op.create_index(
        op.f("ix_delivery_stops_invoice_id"),
        "delivery_stops",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivery_stops_trip_id"), "delivery_stops", ["trip_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_stops_trip_id"), table_name="delivery_stops")
    op.drop_index(op.f("ix_delivery_stops_invoice_id"), table_name="delivery_stops")
    op.drop_table("delivery_stops")
    op.drop_index(op.f("ix_delivery_trips_trip_date"), table_name="delivery_trips")
    op.drop_table("delivery_trips")
    # ### end Alembic commands ###
