"""add_tax_types_and_multi_tax_system

Revision ID: 4b8bf387580a
Revises: 0d62568dc739
Create Date: 2026-07-18 00:16:59.675181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8bf387580a'
down_revision: Union[str, None] = '0d62568dc739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accounting_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoice_tax_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('tax_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_at_time', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_tax_lines_invoice_id'), 'invoice_tax_lines', ['invoice_id'], unique=False)
    op.create_table('quotation_tax_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('tax_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_at_time', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales_quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_tax_lines_quotation_id'), 'quotation_tax_lines', ['quotation_id'], unique=False)
    op.create_table('return_tax_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('tax_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_at_time', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_tax_lines_return_id'), 'return_tax_lines', ['return_id'], unique=False)
    op.add_column('customers', sa.Column('tax_exempt', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'tax_exempt')
    op.drop_index(op.f('ix_return_tax_lines_return_id'), table_name='return_tax_lines')
    op.drop_table('return_tax_lines')
    op.drop_index(op.f('ix_quotation_tax_lines_quotation_id'), table_name='quotation_tax_lines')
    op.drop_table('quotation_tax_lines')
    op.drop_index(op.f('ix_invoice_tax_lines_invoice_id'), table_name='invoice_tax_lines')
    op.drop_table('invoice_tax_lines')
    op.drop_table('tax_types')
    # ### end Alembic commands ###
