"""add user permissions column

Revision ID: 90c90a0ec9eb
Revises: 461ceac8fe5a
Create Date: 2026-07-17 01:09:46.882226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90c90a0ec9eb"
down_revision: Union[str, None] = "461ceac8fe5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("permissions", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
