"""add invoice fulfillment and pickup timestamp

Revision ID: aaecbb2f94c2
Revises: 45655a343b3e
Create Date: 2026-07-17 06:06:04.350070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "aaecbb2f94c2"
down_revision: Union[str, None] = "45655a343b3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

fulfillment_type = postgresql.ENUM("pickup", "delivery", name="fulfillmenttype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `op.add_column` does not create the enum type itself (unlike `op.create_table`),
    # so it must be created explicitly first on a fresh database.
    fulfillment_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "sales_invoices",
        sa.Column(
            "fulfillment",
            sa.Enum("pickup", "delivery", name="fulfillmenttype", create_type=False),
            server_default="delivery",
            nullable=False,
        ),
    )
    op.add_column(
        "sales_invoices",
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_invoices", "picked_up_at")
    op.drop_column("sales_invoices", "fulfillment")
    fulfillment_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
