"""add_expenses_table_and_update_cashier_payments

Revision ID: e7094678ec0c
Revises: 6a4b334057c7
Create Date: 2026-07-18 13:23:35.491695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7094678ec0c'
down_revision: Union[str, None] = '6a4b334057c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('utilities', 'food', 'water', 'rent', 'salaries', 'transport', 'maintenance', 'office', 'other', name='expensecategory'), nullable=False),
    sa.Column('payee_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'credit', name='expensepaymentmethod'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('reference_no', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add reference_type and reference_id as nullable first, backfill, then make NOT NULL.
    op.add_column('cashier_payments', sa.Column('reference_type', sa.String(length=30), nullable=True))
    op.add_column('cashier_payments', sa.Column('reference_id', sa.Integer(), nullable=True))
    op.execute("UPDATE cashier_payments SET reference_type = 'sales', reference_id = 0")
    op.alter_column('cashier_payments', 'reference_type', nullable=False)
    op.alter_column('cashier_payments', 'reference_id', nullable=False)
    op.alter_column('cashier_payments', 'payment_method',
               existing_type=postgresql.ENUM('cash', 'credit', name='salespaymentmethod'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_cashier_payments_invoice_id'), table_name='cashier_payments')
    op.create_index(op.f('ix_cashier_payments_reference_id'), 'cashier_payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_cashier_payments_reference_type'), 'cashier_payments', ['reference_type'], unique=False)
    op.drop_constraint(op.f('cashier_payments_invoice_id_fkey'), 'cashier_payments', type_='foreignkey')
    op.drop_column('cashier_payments', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashier_payments', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cashier_payments_invoice_id_fkey'), 'cashier_payments', 'sales_invoices', ['invoice_id'], ['id'])
    op.drop_index(op.f('ix_cashier_payments_reference_type'), table_name='cashier_payments')
    op.drop_index(op.f('ix_cashier_payments_reference_id'), table_name='cashier_payments')
    op.create_index(op.f('ix_cashier_payments_invoice_id'), 'cashier_payments', ['invoice_id'], unique=False)
    op.alter_column('cashier_payments', 'payment_method',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('cash', 'credit', name='salespaymentmethod'),
               existing_nullable=False)
    op.drop_column('cashier_payments', 'reference_id')
    op.drop_column('cashier_payments', 'reference_type')
    op.drop_table('expenses')
    # ### end Alembic commands ###
