"""Import all models here so Base.metadata knows every table (needed by create_all/Alembic)."""

from app.domain.models.accounting import Account, AccountType, JournalEntry, JournalItem
from app.domain.models.delivery import (
    DeliveryStop,
    DeliveryTrip,
    StopStatus,
    TripStatus,
)
from app.domain.models.expenses import (
    Expense,
    ExpenseCategory,
    ExpensePaymentMethod,
)
from app.domain.models.inventory import (
    AdjustmentType,
    Product,
    ProductBatch,
    ProductUnit,
    StockAdjustment,
    StockAdjustmentLine,
    Warehouse,
)
from app.domain.models.purchases import (
    PurchaseInvoice,
    PurchaseInvoiceLine,
    PurchasePaymentMethod,
    PurchaseReturn,
    PurchaseReturnLine,
    PurchaseReturnReason,
    Supplier,
    SupplierPayment,
)
from app.domain.models.sales import (
    CashierPayment,
    Customer,
    CustomerPayment,
    FulfillmentType,
    InvoiceTaxLine,
    PriceTier,
    QuotationStatus,
    QuotationTaxLine,
    ReturnReason,
    ReturnTaxLine,
    SalesInvoice,
    SalesInvoiceLine,
    SalesPaymentMethod,
    SalesQuotation,
    SalesQuotationLine,
    SalesReturn,
    SalesReturnLine,
    TaxType,
)
from app.domain.models.user import User, UserRole

__all__ = [
    "Account",
    "AccountType",
    "AdjustmentType",
    "CashierPayment",
    "Customer",
    "CustomerPayment",
    "DeliveryStop",
    "DeliveryTrip",
    "Expense",
    "ExpenseCategory",
    "ExpensePaymentMethod",
    "FulfillmentType",
    "InvoiceTaxLine",
    "JournalEntry",
    "JournalItem",
    "PriceTier",
    "Product",
    "ProductBatch",
    "ProductUnit",
    "PurchaseInvoice",
    "PurchaseInvoiceLine",
    "PurchasePaymentMethod",
    "PurchaseReturn",
    "PurchaseReturnLine",
    "PurchaseReturnReason",
    "QuotationStatus",
    "QuotationTaxLine",
    "ReturnReason",
    "ReturnTaxLine",
    "SalesInvoice",
    "SalesInvoiceLine",
    "SalesPaymentMethod",
    "SalesQuotation",
    "SalesQuotationLine",
    "SalesReturn",
    "SalesReturnLine",
    "StopStatus",
    "StockAdjustment",
    "StockAdjustmentLine",
    "Supplier",
    "SupplierPayment",
    "TaxType",
    "TripStatus",
    "User",
    "UserRole",
    "Warehouse",
]
